#
# Autogenerated file, DO NOT EDIT
#

#
# Files matching regexps:
#
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-preprocess.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-validate.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-parse.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-uninstall.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-build.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-digest.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-install.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-clean.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-initialize.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/sitetool-check.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/map-sxml.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/svnlog-wikitext.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/changelog-wikitext.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/wikitext-sxml.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/sxml-sxml.in
#  /home/francesco/Sviluppo/sitetool/sitetool/src/filters/news-wikitext.in
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Filterchain.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Sitemap.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/SXML.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Graphviz.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Parse.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Pagemap.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Array.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Configuration.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Autoconfig.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Stack.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Tree.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Scheme.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Preprocess.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/XML.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Digest.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Variable.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/WWW/HTTP.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/WWW/MAILTO.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/WWW/HREF.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/WWW/FTP.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/WWW/HTTPS.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Misc/Email.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/Shell.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/Directory.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/File.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/String.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/Filename.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/OS/Environment.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Base/Debug.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Base/Trace.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Base/Options.pm
#  /home/francesco/Sviluppo/sitetool/sitetool/libs/perl/Sitetool/Base/Program.pm
#

AC_DEFUN([PERL_AUTOFRISK_CHECKS],[
AX_PROG_PERL_MODULES([Sitetool::WWW::MAILTO])
AX_PROG_PERL_MODULES([Sitetool::Graphviz])
AX_PROG_PERL_MODULES([Sitetool::OS::String])
AX_PROG_PERL_MODULES([POSIX qw(&exit EXIT_FAILURE EXIT_SUCCESS)])
AX_PROG_PERL_MODULES([Sitetool::SXML])
AX_PROG_PERL_MODULES([Sitetool::OS::Shell])
AX_PROG_PERL_MODULES([Sitetool::Pagemap])
AX_PROG_PERL_MODULES([File::Path])
AX_PROG_PERL_MODULES([Sitetool::Scheme])
AX_PROG_PERL_MODULES([Sitetool::XML])
AX_PROG_PERL_MODULES([Sitetool::Base::Debug])
AX_PROG_PERL_MODULES([File::Copy])
AX_PROG_PERL_MODULES([warnings])
AX_PROG_PERL_MODULES([Sitetool::Variable])
AX_PROG_PERL_MODULES([Data::Dumper])
AX_PROG_PERL_MODULES([Sitetool::Autoconfig])
AX_PROG_PERL_MODULES([Sitetool::Stack])
AX_PROG_PERL_MODULES([Sitetool::OS::Environment])
AX_PROG_PERL_MODULES([Sitetool::Array])
AX_PROG_PERL_MODULES([Sitetool::WWW::FTP])
AX_PROG_PERL_MODULES([strict])
AX_PROG_PERL_MODULES([Sitetool::OS::Filename])
AX_PROG_PERL_MODULES([diagnostics])
AX_PROG_PERL_MODULES([Sitetool::OS::Directory])
AX_PROG_PERL_MODULES([File::Temp])
AX_PROG_PERL_MODULES([Sitetool::WWW::HREF])
AX_PROG_PERL_MODULES([vars qw ( @ISA )])
AX_PROG_PERL_MODULES([File::Spec])
AX_PROG_PERL_MODULES([Sitetool::Filterchain])
AX_PROG_PERL_MODULES([vars qw ( $VERSION $COMPATIBLE $FILENAME )])
AX_PROG_PERL_MODULES([Sitetool::Configuration])
AX_PROG_PERL_MODULES([Sitetool::Preprocess])
AX_PROG_PERL_MODULES([Sitetool::Tree])
AX_PROG_PERL_MODULES([5.8.0])
AX_PROG_PERL_MODULES([Sitetool::WWW::HTTPS])
AX_PROG_PERL_MODULES([Sitetool::Base::Trace])
AX_PROG_PERL_MODULES([Sitetool::WWW::HTTP])
AX_PROG_PERL_MODULES([Sitetool::Base::Program])
AX_PROG_PERL_MODULES([Sitetool::Sitemap])
AX_PROG_PERL_MODULES([Sitetool::Digest])
AX_PROG_PERL_MODULES([Exporter])
AX_PROG_PERL_MODULES([Carp])
AX_PROG_PERL_MODULES([Sitetool::Parse])
AX_PROG_PERL_MODULES([Sitetool::OS::File])
AX_PROG_PERL_MODULES([File::Basename])
AX_PROG_PERL_MODULES([vars qw (@ISA @EXPORT)])
AX_PROG_PERL_MODULES([Cwd])
])

AC_DEFUN([PERL_AUTOFRISK_SUMMARY],[
])
